[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = ""
  command = "npm run build"
  publish = "build/"

# This a rule for Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
